In [1]:
# Task 1.1

# a - не получится перемножить матрицы
# б - можем вычислить произведение мтрицы А на В с размерностью 2*3
# в - можно вычислить произведение АВ с размерностью 8*8 и произведение ВА с размерностью 3*3
# г - можно вычислить произведения АВ и ВА - обе с размерностью 4*4

In [1]:
# Task 1.2

import numpy as np


A = [[1, -2], [3, 0]]
B = [[4, -1], [0, 5]]


def transpose(B):
    new_B = []
    for j, vj in enumerate(range(len(B[0]))):
        new_B_i = []
        for i, vi in enumerate(B):
            new_B_i.append(B[i][vj])
        new_B.append(new_B_i)
    return new_B


def m_sum(A, B):
    C = []
    if len(A) == len(B) and len(A[0]) == len(B[0]):
        for i in range(len(A)):
            line = []
            for j in range(len(A[i])):
                val = A[i][j] + B[i][j]
                line.append(val)
            C.append(line)
        return C
    else:
        return print('You are not allowed to sum these matrixes')


def multiply(A, B):
    matrix = []
    for i in range(len(A)):
        line = []
        for q in range(len(B[0])):
            val = int()
            for j in range(len(A[i])):
                int_val = A[i][j] * B[j][q]
                val += int_val
            line.append(val)
        matrix.append(line)
    if len(A[0]) == len(B):
        return matrix
    else:
        return print('You are not allowed to multiply such matrixes')

    
def const_multiply(n, A):
    matrix = []
    for i in range(len(A)):
        line = []
        for j in range(len(A[i])):
            val = n * A[i][j]
            line.append(val)
        matrix.append(line)
    return matrix


transpose(A)
m_sum(A, B)
multiply(A, B)
multiply(B, A)


# Проверка через NumPy

A1 = np.array([[1, -2], [3, 0]])
B1 = np.array([[4, -1], [0, 5]])

A1 + B1
A1.dot(B1)
B1.dot(A1)

array([[ 1, -8],
       [15,  0]])

In [2]:
# Task 1.3

A = [[1, 7], [3, 6]]
B = [[0, 5], [2, -1]]
C = [[2, -4], [1, 1]]

m_sum(m_sum(const_multiply(3, A), const_multiply(-2, B)), const_multiply(4, C))

# Проверка NumPy

A1 = np.array([[1, 7], [3, 6]])
B1 = np.array([[0, 5], [2, -1]])
C1 = np.array([[2, -4], [1, 1]])

3 * A1 + (-2) * B1 + 4 * C1


array([[11, -5],
       [ 9, 24]])

In [3]:
# Task 1.4

A = [[4, 1], [5, -2], [2, 3]]

AAT = multiply(A, transpose(A))
ATA = multiply(transpose(A), A)

AAT
ATA


# Проверка через NumPy

A1 = np.array([[4, 1], [5, -2], [2, 3]])

A1.dot(A1.T)
A1.T.dot(A1)

array([[45,  0],
       [ 0, 14]])

In [4]:
# Task 2.1

from numpy import linalg

# a - sin(x) * sin(x) + cos(x) * cos(x) = 1

# б - 4 * 5 *9 = 180

# в - отнимая от третьей строки вторую и от второй - первую, получим две строки со всеми значениями равным числу "3". 
# По признаку того, что две строки равны друг другу, определитель равен: "0"


In [96]:
# Task 2.2

# a - по свойству det(AB) = det(A) * det(B) вычисляем det(A^2): det(A^2) = det(A) * det(A) = 4 * 4 = 16

# б - по свойству det(AT) = det(A) получим, что det(AT) = 4

# в - при вычислении определителя матрицы, умноженной в два раза, все слогаемые будут в два раза больше. 
# Двойку можно вынести за скобки и получится, что определитель матрицы 2 * А будет равен двойному определителю обычной матрицы А
# Ответ: "8"

In [97]:
# Task 2.3

# Вторую строку можно выразить, как первую строку, умноженную на число (-2). 
# По свойству линейной зависимости строк, определитель матрицы равен нулю, что является признаком выражденности

In [5]:
# Task 2.4

# а - третья строка матрицы является линейной комбинацией первой и второй (сложение), поэтому отбросим ей.
# остаются две линейно независимые строки. Соответственно, ранг матрицы равен "2"

# Проверка

A2 = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
linalg.matrix_rank(A2)


# б - третья строка является суммой первой и второй строк, отбросим её. Остаются три линейно независимые строки. 
# Соответственно, ранг матрицы равен "3"

A3 = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
linalg.matrix_rank(A3)


3